### ISSUE TITLE
[JAVA] Unknown column 'delete_yn' in 'field list'

### ISSUE THREAD

**Issue by ro-ssang** [IDWWT/hello-utils#108]
## AS-IS

* 프로젝트 시작시, hello-code 컨테이너가 실행되지 않음.

## TO-BE

* 프로젝트 시작시, hello-code 컨테이너가 실행된다.

## 참고사항

```
2024-03-01 17:44:06 Listening for transport dt_socket at address: 8000
2024-03-01 17:44:09 
2024-03-01 17:44:09   .   ____          _            __ _ _
2024-03-01 17:44:09  /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
2024-03-01 17:44:09 ( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
2024-03-01 17:44:09  \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
2024-03-01 17:44:09   '  |____| .__|_| |_|_| |_\__, | / / / /
2024-03-01 17:44:09  =========|_|==============|___/=/_/_/_/
2024-03-01 17:44:09  :: Spring Boot ::                (v3.2.2)
2024-03-01 17:44:09 
2024-03-01 17:44:10 2024-03-01T08:44:09.980Z  INFO 1 --- [           main] c.h.hellocode.HellocodeApplication       : Starting HellocodeApplication v0.0.1-SNAPSHOT using Java 17.0.2 with PID 1 (/app/hellocode-0.0.1-SNAPSHOT.jar started by root in /app)
2024-03-01 17:44:10 2024-03-01T08:44:10.004Z  INFO 1 --- [           main] c.h.hellocode.HellocodeApplication       : The following 1 profile is active: "local"
2024-03-01 17:44:13 2024-03-01T08:44:13.177Z  INFO 1 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Bootstrapping Spring Data JPA repositories in DEFAULT mode.
2024-03-01 17:44:13 2024-03-01T08:44:13.314Z  INFO 1 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Finished Spring Data repository scanning in 115 ms. Found 1 JPA repository interface.
2024-03-01 17:44:15 2024-03-01T08:44:15.454Z  INFO 1 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port 8080 (http)
2024-03-01 17:44:15 2024-03-01T08:44:15.505Z  INFO 1 --- [           main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2024-03-01 17:44:15 2024-03-01T08:44:15.506Z  INFO 1 --- [           main] o.apache.catalina.core.StandardEngine    : Starting Servlet engine: [Apache Tomcat/10.1.18]
2024-03-01 17:44:15 2024-03-01T08:44:15.692Z  INFO 1 --- [           main] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2024-03-01 17:44:15 2024-03-01T08:44:15.696Z  INFO 1 --- [           main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 5342 ms
2024-03-01 17:44:16 2024-03-01T08:44:16.010Z  INFO 1 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Starting...
2024-03-01 17:44:16 2024-03-01T08:44:16.900Z  INFO 1 --- [           main] com.zaxxer.hikari.pool.HikariPool        : HikariPool-1 - Added connection com.mysql.cj.jdbc.ConnectionImpl@2ce03e86
2024-03-01 17:44:16 2024-03-01T08:44:16.907Z  INFO 1 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Start completed.
2024-03-01 17:44:16 2024-03-01T08:44:16.971Z  WARN 1 --- [           main] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'dataSourceScriptDatabaseInitializer' defined in class path resource [org/springframework/boot/autoconfigure/sql/init/DataSourceInitializationConfiguration.class]: Failed to execute SQL script statement #1 of URL [jar:nested:/app/hellocode-0.0.1-SNAPSHOT.jar/!BOOT-INF/classes/!/data.sql]: INSERT INTO hello_util.util (category_cd, code, created_at, delete_yn, description, language_cd, title, user_id) VALUES('FORMAT', 'code', NOW(), NULL, 'description', 'JAVASCRIPT', 'title', 'testUser1')
2024-03-01 17:44:16 2024-03-01T08:44:16.971Z  INFO 1 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown initiated...
2024-03-01 17:44:16 2024-03-01T08:44:16.981Z  INFO 1 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown completed.
2024-03-01 17:44:16 2024-03-01T08:44:16.990Z  INFO 1 --- [           main] o.apache.catalina.core.StandardService   : Stopping service [Tomcat]
2024-03-01 17:44:17 2024-03-01T08:44:17.028Z  INFO 1 --- [           main] .s.b.a.l.ConditionEvaluationReportLogger : 
2024-03-01 17:44:17 
2024-03-01 17:44:17 Error starting ApplicationContext. To display the condition evaluation report re-run your application with 'debug' enabled.
2024-03-01 17:44:17 2024-03-01T08:44:17.087Z ERROR 1 --- [           main] o.s.boot.SpringApplication               : Application run failed
2024-03-01 17:44:17 
2024-03-01 17:44:17 org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'dataSourceScriptDatabaseInitializer' defined in class path resource [org/springframework/boot/autoconfigure/sql/init/DataSourceInitializationConfiguration.class]: Failed to execute SQL script statement #1 of URL [jar:nested:/app/hellocode-0.0.1-SNAPSHOT.jar/!BOOT-INF/classes/!/data.sql]: INSERT INTO hello_util.util (category_cd, code, created_at, delete_yn, description, language_cd, title, user_id) VALUES('FORMAT', 'code', NOW(), NULL, 'description', 'JAVASCRIPT', 'title', 'testUser1')
2024-03-01 17:44:17     at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1773) ~[spring-beans-6.1.3.jar!/:6.1.3]
2024-03-01 17:44:17     at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:599) ~[spring-beans-6.1.3.jar!/:6.1.3]
2024-03-01 17:44:17     at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:521) ~[spring-beans-6.1.3.jar!/:6.1.3]
2024-03-01 17:44:17     at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:325) ~[spring-beans-6.1.3.jar!/:6.1.3]
2024-03-01 17:44:17     at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-6.1.3.jar!/:6.1.3]
2024-03-01 17:44:17     at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:323) ~[spring-beans-6.1.3.jar!/:6.1.3]
2024-03-01 17:44:17     at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199) ~[spring-beans-6.1.3.jar!/:6.1.3]
2024-03-01 17:44:17     at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:312) ~[spring-beans-6.1.3.jar!/:6.1.3]
2024-03-01 17:44:17     at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199) ~[spring-beans-6.1.3.jar!/:6.1.3]
2024-03-01 17:44:17     at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1231) ~[spring-context-6.1.3.jar!/:6.1.3]
2024-03-01 17:44:17     at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:949) ~[spring-context-6.1.3.jar!/:6.1.3]
2024-03-01 17:44:17     at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:624) ~[spring-context-6.1.3.jar!/:6.1.3]
2024-03-01 17:44:17     at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:146) ~[spring-boot-3.2.2.jar!/:3.2.2]
2024-03-01 17:44:17     at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:754) ~[spring-boot-3.2.2.jar!/:3.2.2]
2024-03-01 17:44:17     at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:456) ~[spring-boot-3.2.2.jar!/:3.2.2]
2024-03-01 17:44:17     at org.springframework.boot.SpringApplication.run(SpringApplication.java:334) ~[spring-boot-3.2.2.jar!/:3.2.2]
2024-03-01 17:44:17     at org.springframework.boot.SpringApplication.run(SpringApplication.java:1354) ~[spring-boot-3.2.2.jar!/:3.2.2]
2024-03-01 17:44:17     at org.springframework.boot.SpringApplication.run(SpringApplication.java:1343) ~[spring-boot-3.2.2.jar!/:3.2.2]
2024-03-01 17:44:17     at com.helloutils.hellocode.HellocodeApplication.main(HellocodeApplication.java:10) ~[!/:0.0.1-SNAPSHOT]
2024-03-01 17:44:17     at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
2024-03-01 17:44:17     at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[na:na]
2024-03-01 17:44:17     at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
2024-03-01 17:44:17     at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[na:na]
2024-03-01 17:44:17     at org.springframework.boot.loader.launch.Launcher.launch(Launcher.java:91) ~[hellocode-0.0.1-SNAPSHOT.jar:0.0.1-SNAPSHOT]
2024-03-01 17:44:17     at org.springframework.boot.loader.launch.Launcher.launch(Launcher.java:53) ~[hellocode-0.0.1-SNAPSHOT.jar:0.0.1-SNAPSHOT]
2024-03-01 17:44:17     at org.springframework.boot.loader.launch.JarLauncher.main(JarLauncher.java:58) ~[hellocode-0.0.1-SNAPSHOT.jar:0.0.1-SNAPSHOT]
2024-03-01 17:44:17 Caused by: org.springframework.jdbc.datasource.init.ScriptStatementFailedException: Failed to execute SQL script statement #1 of URL [jar:nested:/app/hellocode-0.0.1-SNAPSHOT.jar/!BOOT-INF/classes/!/data.sql]: INSERT INTO hello_util.util (category_cd, code, created_at, delete_yn, description, language_cd, title, user_id) VALUES('FORMAT', 'code', NOW(), NULL, 'description', 'JAVASCRIPT', 'title', 'testUser1')
2024-03-01 17:44:17     at org.springframework.jdbc.datasource.init.ScriptUtils.executeSqlScript(ScriptUtils.java:282) ~[spring-jdbc-6.1.3.jar!/:6.1.3]
2024-03-01 17:44:17     at org.springframework.jdbc.datasource.init.ResourceDatabasePopulator.populate(ResourceDatabasePopulator.java:254) ~[spring-jdbc-6.1.3.jar!/:6.1.3]
2024-03-01 17:44:17     at org.springframework.jdbc.datasource.init.DatabasePopulatorUtils.execute(DatabasePopulatorUtils.java:54) ~[spring-jdbc-6.1.3.jar!/:6.1.3]
2024-03-01 17:44:17     at org.springframework.boot.jdbc.init.DataSourceScriptDatabaseInitializer.runScripts(DataSourceScriptDatabaseInitializer.java:87) ~[spring-boot-3.2.2.jar!/:3.2.2]
2024-03-01 17:44:17     at org.springframework.boot.sql.init.AbstractScriptDatabaseInitializer.runScripts(AbstractScriptDatabaseInitializer.java:146) ~[spring-boot-3.2.2.jar!/:3.2.2]
2024-03-01 17:44:17     at org.springframework.boot.sql.init.AbstractScriptDatabaseInitializer.applyScripts(AbstractScriptDatabaseInitializer.java:108) ~[spring-boot-3.2.2.jar!/:3.2.2]
2024-03-01 17:44:17     at org.springframework.boot.sql.init.AbstractScriptDatabaseInitializer.applyDataScripts(AbstractScriptDatabaseInitializer.java:102) ~[spring-boot-3.2.2.jar!/:3.2.2]
2024-03-01 17:44:17     at org.springframework.boot.sql.init.AbstractScriptDatabaseInitializer.initializeDatabase(AbstractScriptDatabaseInitializer.java:77) ~[spring-boot-3.2.2.jar!/:3.2.2]
2024-03-01 17:44:17     at org.springframework.boot.sql.init.AbstractScriptDatabaseInitializer.afterPropertiesSet(AbstractScriptDatabaseInitializer.java:66) ~[spring-boot-3.2.2.jar!/:3.2.2]
2024-03-01 17:44:17     at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1820) ~[spring-beans-6.1.3.jar!/:6.1.3]
2024-03-01 17:44:17     at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1769) ~[spring-beans-6.1.3.jar!/:6.1.3]
2024-03-01 17:44:17     ... 25 common frames omitted
2024-03-01 17:44:17 Caused by: java.sql.SQLSyntaxErrorException: Unknown column 'delete_yn' in 'field list'
2024-03-01 17:44:17     at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:121) ~[mysql-connector-j-8.3.0.jar!/:8.3.0]
2024-03-01 17:44:17     at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122) ~[mysql-connector-j-8.3.0.jar!/:8.3.0]
2024-03-01 17:44:17     at com.mysql.cj.jdbc.StatementImpl.executeInternal(StatementImpl.java:770) ~[mysql-connector-j-8.3.0.jar!/:8.3.0]
2024-03-01 17:44:17     at com.mysql.cj.jdbc.StatementImpl.execute(StatementImpl.java:653) ~[mysql-connector-j-8.3.0.jar!/:8.3.0]
2024-03-01 17:44:17     at com.zaxxer.hikari.pool.ProxyStatement.execute(ProxyStatement.java:94) ~[HikariCP-5.0.1.jar!/:na]
2024-03-01 17:44:17     at com.zaxxer.hikari.pool.HikariProxyStatement.execute(HikariProxyStatement.java) ~[HikariCP-5.0.1.jar!/:na]
2024-03-01 17:44:17     at org.springframework.jdbc.datasource.init.ScriptUtils.executeSqlScript(ScriptUtils.java:261) ~[spring-jdbc-6.1.3.jar!/:6.1.3]
2024-03-01 17:44:17     ... 35 common frames omitted
2024-03-01 17:44:17 
2024-03-01 17:45:27 Listening for transport dt_socket at address: 8000
2024-03-01 17:45:29 
2024-03-01 17:45:29   .   ____          _            __ _ _
2024-03-01 17:45:29  /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
2024-03-01 17:45:29 ( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
2024-03-01 17:45:29  \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
2024-03-01 17:45:29   '  |____| .__|_| |_|_| |_\__, | / / / /
2024-03-01 17:45:29  =========|_|==============|___/=/_/_/_/
2024-03-01 17:45:29  :: Spring Boot ::                (v3.2.2)
2024-03-01 17:45:29 
2024-03-01 17:45:30 2024-03-01T08:45:30.045Z  INFO 1 --- [           main] c.h.hellocode.HellocodeApplication       : Starting HellocodeApplication v0.0.1-SNAPSHOT using Java 17.0.2 with PID 1 (/app/hellocode-0.0.1-SNAPSHOT.jar started by root in /app)
2024-03-01 17:45:30 2024-03-01T08:45:30.084Z  INFO 1 --- [           main] c.h.hellocode.HellocodeApplication       : The following 1 profile is active: "local"
2024-03-01 17:45:32 2024-03-01T08:45:32.407Z  INFO 1 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Bootstrapping Spring Data JPA repositories in DEFAULT mode.
2024-03-01 17:45:32 2024-03-01T08:45:32.538Z  INFO 1 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Finished Spring Data repository scanning in 113 ms. Found 1 JPA repository interface.
2024-03-01 17:45:33 2024-03-01T08:45:33.712Z  INFO 1 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port 8080 (http)
2024-03-01 17:45:33 2024-03-01T08:45:33.739Z  INFO 1 --- [           main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2024-03-01 17:45:33 2024-03-01T08:45:33.740Z  INFO 1 --- [           main] o.apache.catalina.core.StandardEngine    : Starting Servlet engine: [Apache Tomcat/10.1.18]
2024-03-01 17:45:33 2024-03-01T08:45:33.837Z  INFO 1 --- [           main] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2024-03-01 17:45:33 2024-03-01T08:45:33.840Z  INFO 1 --- [           main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 3473 ms
2024-03-01 17:45:34 2024-03-01T08:45:34.092Z  INFO 1 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Starting...
2024-03-01 17:45:34 2024-03-01T08:45:34.666Z  INFO 1 --- [           main] com.zaxxer.hikari.pool.HikariPool        : HikariPool-1 - Added connection com.mysql.cj.jdbc.ConnectionImpl@63a9c661
2024-03-01 17:45:34 2024-03-01T08:45:34.673Z  INFO 1 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Start completed.
2024-03-01 17:45:34 2024-03-01T08:45:34.716Z  WARN 1 --- [           main] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'dataSourceScriptDatabaseInitializer' defined in class path resource [org/springframework/boot/autoconfigure/sql/init/DataSourceInitializationConfiguration.class]: Failed to execute SQL script statement #1 of URL [jar:nested:/app/hellocode-0.0.1-SNAPSHOT.jar/!BOOT-INF/classes/!/data.sql]: INSERT INTO hello_util.util (category_cd, code, created_at, delete_yn, description, language_cd, title, user_id) VALUES('FORMAT', 'code', NOW(), NULL, 'description', 'JAVASCRIPT', 'title', 'testUser1')
2024-03-01 17:45:34 2024-03-01T08:45:34.716Z  INFO 1 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown initiated...
2024-03-01 17:45:34 2024-03-01T08:45:34.722Z  INFO 1 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown completed.
2024-03-01 17:45:34 2024-03-01T08:45:34.729Z  INFO 1 --- [           main] o.apache.catalina.core.StandardService   : Stopping service [Tomcat]
2024-03-01 17:45:34 2024-03-01T08:45:34.757Z  INFO 1 --- [           main] .s.b.a.l.ConditionEvaluationReportLogger : 
2024-03-01 17:45:34 
2024-03-01 17:45:34 Error starting ApplicationContext. To display the condition evaluation report re-run your application with 'debug' enabled.
2024-03-01 17:45:34 2024-03-01T08:45:34.796Z ERROR 1 --- [           main] o.s.boot.SpringApplication               : Application run failed
2024-03-01 17:45:34 
2024-03-01 17:45:34 org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'dataSourceScriptDatabaseInitializer' defined in class path resource [org/springframework/boot/autoconfigure/sql/init/DataSourceInitializationConfiguration.class]: Failed to execute SQL script statement #1 of URL [jar:nested:/app/hellocode-0.0.1-SNAPSHOT.jar/!BOOT-INF/classes/!/data.sql]: INSERT INTO hello_util.util (category_cd, code, created_at, delete_yn, description, language_cd, title, user_id) VALUES('FORMAT', 'code', NOW(), NULL, 'description', 'JAVASCRIPT', 'title', 'testUser1')
2024-03-01 17:45:34     at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1773) ~[spring-beans-6.1.3.jar!/:6.1.3]
2024-03-01 17:45:34     at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:599) ~[spring-beans-6.1.3.jar!/:6.1.3]
2024-03-01 17:45:34     at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:521) ~[spring-beans-6.1.3.jar!/:6.1.3]
2024-03-01 17:45:34     at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:325) ~[spring-beans-6.1.3.jar!/:6.1.3]
2024-03-01 17:45:34     at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-6.1.3.jar!/:6.1.3]
2024-03-01 17:45:34     at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:323) ~[spring-beans-6.1.3.jar!/:6.1.3]
2024-03-01 17:45:34     at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199) ~[spring-beans-6.1.3.jar!/:6.1.3]
2024-03-01 17:45:34     at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:312) ~[spring-beans-6.1.3.jar!/:6.1.3]
2024-03-01 17:45:34     at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199) ~[spring-beans-6.1.3.jar!/:6.1.3]
2024-03-01 17:45:34     at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1231) ~[spring-context-6.1.3.jar!/:6.1.3]
2024-03-01 17:45:34     at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:949) ~[spring-context-6.1.3.jar!/:6.1.3]
2024-03-01 17:45:34     at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:624) ~[spring-context-6.1.3.jar!/:6.1.3]
2024-03-01 17:45:34     at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:146) ~[spring-boot-3.2.2.jar!/:3.2.2]
2024-03-01 17:45:34     at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:754) ~[spring-boot-3.2.2.jar!/:3.2.2]
2024-03-01 17:45:34     at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:456) ~[spring-boot-3.2.2.jar!/:3.2.2]
2024-03-01 17:45:34     at org.springframework.boot.SpringApplication.run(SpringApplication.java:334) ~[spring-boot-3.2.2.jar!/:3.2.2]
2024-03-01 17:45:34     at org.springframework.boot.SpringApplication.run(SpringApplication.java:1354) ~[spring-boot-3.2.2.jar!/:3.2.2]
2024-03-01 17:45:34     at org.springframework.boot.SpringApplication.run(SpringApplication.java:1343) ~[spring-boot-3.2.2.jar!/:3.2.2]
2024-03-01 17:45:34     at com.helloutils.hellocode.HellocodeApplication.main(HellocodeApplication.java:10) ~[!/:0.0.1-SNAPSHOT]
2024-03-01 17:45:34     at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
2024-03-01 17:45:34     at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[na:na]
2024-03-01 17:45:34     at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
2024-03-01 17:45:34     at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[na:na]
2024-03-01 17:45:34     at org.springframework.boot.loader.launch.Launcher.launch(Launcher.java:91) ~[hellocode-0.0.1-SNAPSHOT.jar:0.0.1-SNAPSHOT]
2024-03-01 17:45:34     at org.springframework.boot.loader.launch.Launcher.launch(Launcher.java:53) ~[hellocode-0.0.1-SNAPSHOT.jar:0.0.1-SNAPSHOT]
2024-03-01 17:45:34     at org.springframework.boot.loader.launch.JarLauncher.main(JarLauncher.java:58) ~[hellocode-0.0.1-SNAPSHOT.jar:0.0.1-SNAPSHOT]
2024-03-01 17:45:34 Caused by: org.springframework.jdbc.datasource.init.ScriptStatementFailedException: Failed to execute SQL script statement #1 of URL [jar:nested:/app/hellocode-0.0.1-SNAPSHOT.jar/!BOOT-INF/classes/!/data.sql]: INSERT INTO hello_util.util (category_cd, code, created_at, delete_yn, description, language_cd, title, user_id) VALUES('FORMAT', 'code', NOW(), NULL, 'description', 'JAVASCRIPT', 'title', 'testUser1')
2024-03-01 17:45:34     at org.springframework.jdbc.datasource.init.ScriptUtils.executeSqlScript(ScriptUtils.java:282) ~[spring-jdbc-6.1.3.jar!/:6.1.3]
2024-03-01 17:45:34     at org.springframework.jdbc.datasource.init.ResourceDatabasePopulator.populate(ResourceDatabasePopulator.java:254) ~[spring-jdbc-6.1.3.jar!/:6.1.3]
2024-03-01 17:45:34     at org.springframework.jdbc.datasource.init.DatabasePopulatorUtils.execute(DatabasePopulatorUtils.java:54) ~[spring-jdbc-6.1.3.jar!/:6.1.3]
2024-03-01 17:45:34     at org.springframework.boot.jdbc.init.DataSourceScriptDatabaseInitializer.runScripts(DataSourceScriptDatabaseInitializer.java:87) ~[spring-boot-3.2.2.jar!/:3.2.2]
2024-03-01 17:45:34     at org.springframework.boot.sql.init.AbstractScriptDatabaseInitializer.runScripts(AbstractScriptDatabaseInitializer.java:146) ~[spring-boot-3.2.2.jar!/:3.2.2]
2024-03-01 17:45:34     at org.springframework.boot.sql.init.AbstractScriptDatabaseInitializer.applyScripts(AbstractScriptDatabaseInitializer.java:108) ~[spring-boot-3.2.2.jar!/:3.2.2]
2024-03-01 17:45:34     at org.springframework.boot.sql.init.AbstractScriptDatabaseInitializer.applyDataScripts(AbstractScriptDatabaseInitializer.java:102) ~[spring-boot-3.2.2.jar!/:3.2.2]
2024-03-01 17:45:34     at org.springframework.boot.sql.init.AbstractScriptDatabaseInitializer.initializeDatabase(AbstractScriptDatabaseInitializer.java:77) ~[spring-boot-3.2.2.jar!/:3.2.2]
2024-03-01 17:45:34     at org.springframework.boot.sql.init.AbstractScriptDatabaseInitializer.afterPropertiesSet(AbstractScriptDatabaseInitializer.java:66) ~[spring-boot-3.2.2.jar!/:3.2.2]
2024-03-01 17:45:34     at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1820) ~[spring-beans-6.1.3.jar!/:6.1.3]
2024-03-01 17:45:34     at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1769) ~[spring-beans-6.1.3.jar!/:6.1.3]
2024-03-01 17:45:34     ... 25 common frames omitted
2024-03-01 17:45:34 Caused by: java.sql.SQLSyntaxErrorException: Unknown column 'delete_yn' in 'field list'
2024-03-01 17:45:34     at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:121) ~[mysql-connector-j-8.3.0.jar!/:8.3.0]
2024-03-01 17:45:34     at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122) ~[mysql-connector-j-8.3.0.jar!/:8.3.0]
2024-03-01 17:45:34     at com.mysql.cj.jdbc.StatementImpl.executeInternal(StatementImpl.java:770) ~[mysql-connector-j-8.3.0.jar!/:8.3.0]
2024-03-01 17:45:34     at com.mysql.cj.jdbc.StatementImpl.execute(StatementImpl.java:653) ~[mysql-connector-j-8.3.0.jar!/:8.3.0]
2024-03-01 17:45:34     at com.zaxxer.hikari.pool.ProxyStatement.execute(ProxyStatement.java:94) ~[HikariCP-5.0.1.jar!/:na]
2024-03-01 17:45:34     at com.zaxxer.hikari.pool.HikariProxyStatement.execute(HikariProxyStatement.java) ~[HikariCP-5.0.1.jar!/:na]
2024-03-01 17:45:34     at org.springframework.jdbc.datasource.init.ScriptUtils.executeSqlScript(ScriptUtils.java:261) ~[spring-jdbc-6.1.3.jar!/:6.1.3]
2024-03-01 17:45:34     ... 35 common frames omitted
2024-03-01 17:45:34 

```

**Comment by ro-ssang** [comment]
data 디렉토리 삭제하고 다시 restart 하니 해결
